# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Example_Model.py
# Created on: 2015-05-15 11:06:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Example_Model <Distance__value_or_field_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Distance__value_or_field_ = arcpy.GetParameterAsText(0)
if Distance__value_or_field_ == '#' or not Distance__value_or_field_:
    Distance__value_or_field_ = "500 Meters" # provide a default value if unspecified

# Local variables:
Cuerpo_de_agua = "Cuerpo de agua"
CAgu_Buffer = Distance__value_or_field_
CAgu_Buffer_Clip = CAgu_Buffer
Results = CAgu_Buffer_Clip
Manzana = "Manzana"

# Process: Buffer
arcpy.Buffer_analysis(Cuerpo_de_agua, CAgu_Buffer, Distance__value_or_field_, "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Clip
arcpy.Clip_analysis(Manzana, CAgu_Buffer, CAgu_Buffer_Clip, "")

# Process: Import Data
arcpy.CartoDBImportToolbox_CartoDB( "your_user", "your_key", "F:\\data\\your_Data.gdb\\yourFeature")

